services:
  api:
    container_name: api
    build: ./api
    ports:
      - 9090:8080
    tty: true
    volumes:
      - ./api:/workspace:cached

  web:
    container_name: web
    build: ./web
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_SERVER=http://localhost:9090/api
    tty: true
    volumes:
      - ./web:/workspace:cached
    depends_on:
      - api
